Vagrant.configure("2") do |config|
  config.vm.box = "centos-base"
  config.vm.network "private_network", ip: "192.168.33.11", auto_config: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "node0"
  end
  config.vm.provision "shell", path: "./init.sh"
end
