Vagrant.configure("2") do |config|
  $num_instances = 6
  (1..$num_instances).each do |i|
	config.vm.define "cluster-node#{i}" do |node|
      node.vm.box = "centos-base"
      node.vm.hostname = "cluster-node#{i}"
      ip = "192.168.33.2#{i}"
      node.vm.network "private_network", ip: ip, auto_config: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "cluster-node#{i}"
      end
      node.vm.provision "shell", path: "./init.sh", args: [i, ip]
    end
  end	  
end
