Vagrant.configure("2") do |config|
  $num_instances = 3
  (1..$num_instances).each do |i|
	config.vm.define "node#{i}" do |node|
      node.vm.box = "centos-base"
      node.vm.hostname = "node#{i}"
      ip = "192.168.33.1#{i}"
      node.vm.network "private_network", ip: ip, auto_config: true
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
      end
      node.vm.provision "shell", path: "./init.sh", args: [i, ip]
    end
  end	  
end
